=== JohnnyYuVe/TESINA/GameOfHistory/XML _FILE/DTD_SCHEMA/ARTICOLO_STRUTTURA.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT RECORD_ARTICOLO (ARTICOLO*)>
<!ELEMENT ARTICOLO (Nome, Prezzo, Descrizione, IMG+)>

<!ATTLIST ARTICOLO 
          ART_ID ID #REQUIRED>

<!ATTLIST ARTICOLO           
          Categoria CDATA #REQUIRED>
<!ATTLIST ARTICOLO           
          HIDE CDATA #REQUIRED>          

<!ELEMENT Nome (#PCDATA)>
<!ELEMENT Prezzo (#PCDATA)>
<!ELEMENT Descrizione (#PCDATA)>


<!ELEMENT IMG (Percorso, Nome_IMG, Estensione)>
<!ELEMENT Percorso (#PCDATA)>
<!ELEMENT Nome_IMG (#PCDATA)>
<!ELEMENT Estensione (#PCDATA)>

=== JohnnyYuVe/TESINA/GameOfHistory/XML _FILE/XML/ARTICOLO1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RECORD_ARTICOLO SYSTEM "http://localhost/php_program/GameOfHistory/XML%20_FILE/DTD_SCHEMA/ARTICOLO_STRUTTURA.dtd">
<RECORD_ARTICOLO>
	
<ARTICOLO ART_ID="ART003" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>1,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO><ARTICOLO ART_ID="ART004" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>2,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO><ARTICOLO ART_ID="ART005" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>3,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO><ARTICOLO ART_ID="ART006" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>4,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO><ARTICOLO ART_ID="ART007" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>5,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO><ARTICOLO ART_ID="ART008" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>6,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO><ARTICOLO ART_ID="ART0009" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>7,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO><ARTICOLO ART_ID="ART010" Categoria="AZIONE"><Nome>God of war</Nome><Prezzo>8,99</Prezzo><Descrizione>Gioco bellissimo</Descrizione><IMG><Percorso>http://localhost/php_program/GameOfHistory/IMG_FILE/</Percorso><Nome_IMG>bowling-alley-with-neon-lights</Nome_IMG><Estensione>.jpg</Estensione></IMG></ARTICOLO></RECORD_ARTICOLO>
