=== JohnnyYuVe/TESINA/GameOfHistory/XML _FILE/DTD_SCHEMA/UTENTE_STRUTTURA.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT RECORD_UTENTE (Utente*)>

<!ELEMENT Utente (INFO_PERSONA+, Data_Registrazione, Punti_History, Membership)>

<!ATTLIST Utente 
          Privieggio (ADMIN | GESTORE | AMMINISTRATORE | CLIENTE | NONE) "NONE" >


<!ELEMENT INFO_PERSONA (Nome, Cognome, Eta, Email, Password, Sesso)> 
<!ATTLIST INFO_PERSONA 
		  ID_Persona ID  #REQUIRED>

<!ELEMENT Nome (#PCDATA)>
<!ELEMENT Cognome (#PCDATA)>
<!ELEMENT Eta (#PCDATA)>  
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Sesso (#PCDATA)> 

<!ELEMENT Data_Registrazione (#PCDATA)>
<!ELEMENT Punti_History (#PCDATA)>
<!ELEMENT Membership (#PCDATA)>

=== JohnnyYuVe/TESINA/GameOfHistory/XML _FILE/XML/UTENTE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RECORD_UTENTE SYSTEM "http://localhost/php_program/GameOfHistory/XML%20_FILE/DTD_SCHEMA/UTENTE_STRUTTURA.dtd">
<RECORD_UTENTE>
	<Utente Privieggio="ADMIN">
				
				<INFO_PERSONA ID_Persona="Uno1">
							<Nome>a</Nome>
							<Cognome>aa</Cognome>
							<Eta>4aaaa</Eta>
							<Email>1234</Email>							
							<Password>1234</Password>
							<Sesso>MASCHIO</Sesso>
				</INFO_PERSONA>

				<Data_Registrazione>09/10/2024</Data_Registrazione>
				<Punti_History>0</Punti_History>
				<Membership>BRONZE</Membership>

		</Utente>

		<Utente Privieggio="CLIENTE">
				
				<INFO_PERSONA ID_Persona="Uno2">
							<Nome>a</Nome>
							<Cognome>aa</Cognome>
							<Eta>4aaaa</Eta>
							<Email>3aaa</Email>						
							<Password>1234</Password>
							<Sesso>MASCHIO</Sesso>
				</INFO_PERSONA>

				<Data_Registrazione>09/10/2024</Data_Registrazione>
				<Punti_History>0</Punti_History>
				<Membership>BRONZE</Membership>

		</Utente>

		<Utente Privieggio="ADMIN">
				
				<INFO_PERSONA ID_Persona="Uno3">
							<Nome>a</Nome>
							<Cognome>aa</Cognome>
							<Eta>4aaaa</Eta>
							<Email>5aaa</Email>							
							<Password>1234</Password>
							<Sesso>MASCHIO</Sesso>
				</INFO_PERSONA>

				<Data_Registrazione>09/10/2024</Data_Registrazione>
				<Punti_History>0</Punti_History>
				<Membership>BRONZE</Membership>

		</Utente>

</RECORD_UTENTE>
